In [1]:
import sys
from pathlib import Path
import pandas as pd
from experiments import result_utils

# Configuration
dir_agent_map = {
    "bqlearning": "Jax Bayesian QLearner",
    "qlearning": "Jax QLearner",
    "actinf": "JAX_AIF",
    "dbs": "DBS"
}

results_dir = Path("../../results/hyperparameters")

# Analyze all agents across all noise levels
print("Analyzing hyperparameter results...")
results_by_noise = result_utils.analyze_best_agents_per_noise(results_dir, dir_agent_map)

# Get top 10 agents for each noise level
top_agents = result_utils.get_top_n_agents(results_by_noise, n=100)

# Format for display
formatted_results = result_utils.format_results_for_display(top_agents, decimals=2)

print(f"Analysis complete! Found {len(formatted_results)} noise levels.")

Analyzing hyperparameter results...
Analysis complete! Found 3 noise levels.

In [2]:
# Display results as 6 separate tables (one for each noise level)
for noise_level in sorted(formatted_results.keys()):
    print(f"\n{'='*100}")
    print(f"NOISE LEVEL: {noise_level}")
    print(f"{'='*100}\n")
    
    df = formatted_results[noise_level]
    # Add rank column
    df_display = df.copy()
    df_display.insert(0, 'Rank', range(1, len(df_display) + 1))
    
    display(df_display)

====================================================================================================
NOISE LEVEL: 0.0
====================================================================================================

    Rank    Agent Type         Hyperparameters  Mean Score  Num Repetitions
0      1  Jax QLearner  QLearner_0.9_0.9_0.1_1     2747.10                5
1      2  Jax QLearner  QLearner_0.9_0.5_0.1_2     2694.13                5
2      3  Jax QLearner  QLearner_0.5_0.5_0.1_1     2662.23                5
3      4  Jax QLearner  QLearner_0.5_0.5_0.1_2     2598.90                5
4      5  Jax QLearner  QLearner_0.9_0.5_0.1_1     2588.92                5
..   ...           ...                     ...         ...              ...
85    86  Jax QLearner    QLearner_0.1_0.9_0_5     1812.73                5
86    87  Jax QLearner    QLearner_0.1_0.9_0_4     1809.52                5
87    88  Jax QLearner    QLearner_0.5_0.9_0_4     1805.37                5
88    89  Jax QLearner    QLearner_0.9_0.9_0_5     1801.08                5
89    90  Jax QLearner    QLearner_0.5_0.9_0_5     1796.25                5

[90 rows x 5 columns]

====================================================================================================
NOISE LEVEL: 0.05
====================================================================================================

    Rank    Agent Type         Hyperparameters  Mean Score  Num Repetitions
0      1  Jax QLearner  QLearner_0.9_0.9_0.1_1     2522.26                5
1      2  Jax QLearner  QLearner_0.5_0.5_0.1_1     2482.80                5
2      3  Jax QLearner  QLearner_0.5_0.9_0.1_1     2466.93                5
3      4  Jax QLearner  QLearner_0.5_0.5_0.1_2     2448.82                5
4      5  Jax QLearner  QLearner_0.9_0.5_0.1_1     2342.69                5
..   ...           ...                     ...         ...              ...
85    86  Jax QLearner    QLearner_0.1_0.9_0_3     1792.43                5
86    87  Jax QLearner    QLearner_0.1_0.9_0_2     1791.15                5
87    88  Jax QLearner    QLearner_0.1_0.9_0_4     1784.46                5
88    89  Jax QLearner    QLearner_0.1_0.9_0_5     1781.05                5
89    90  Jax QLearner    QLearner_0.1_0.9_0_1     1775.81                5

[90 rows x 5 columns]

====================================================================================================
NOISE LEVEL: 0.1
====================================================================================================

    Rank    Agent Type         Hyperparameters  Mean Score  Num Repetitions
0      1  Jax QLearner  QLearner_0.9_0.9_0.1_1     2405.98                5
1      2  Jax QLearner  QLearner_0.5_0.9_0.1_1     2348.86                5
2      3  Jax QLearner  QLearner_0.5_0.5_0.1_1     2346.97                5
3      4  Jax QLearner  QLearner_0.5_0.5_0.1_2     2302.89                5
4      5  Jax QLearner  QLearner_0.9_0.5_0.1_1     2255.18                5
..   ...           ...                     ...         ...              ...
85    86  Jax QLearner    QLearner_0.1_0.9_0_5     1809.70                5
86    87  Jax QLearner    QLearner_0.1_0.9_0_2     1808.90                5
87    88  Jax QLearner    QLearner_0.1_0.9_0_4     1808.67                5
88    89  Jax QLearner    QLearner_0.1_0.9_0_3     1807.15                5
89    90  Jax QLearner    QLearner_0.1_0.9_0_1     1798.79                5

[90 rows x 5 columns]

In [ ]:
# Calculate average scores across all noise levels for each agent
print(f"\n{'='*100}")
print("AVERAGE SCORES ACROSS ALL NOISE LEVELS")
print(f"{'='*100}\n")

# Combine all results across noise levels
all_results = []
for noise_level, df in formatted_results.items():
    df_copy = df.copy()
    df_copy['noise_level'] = noise_level
    all_results.append(df_copy)

combined_df = pd.concat(all_results, ignore_index=True)

# Calculate average score for each agent across all noise levels
avg_scores = combined_df.groupby('Hyperparameters')['Mean Score'].mean().sort_values(ascending=False)
avg_scores_df = pd.DataFrame({
    'Hyperparameters': avg_scores.index,
    'Mean Score': avg_scores.values
})

# Add rank column
avg_scores_df.insert(0, 'Rank', range(1, len(avg_scores_df) + 1))

# Reset index for clean display
avg_scores_df = avg_scores_df.reset_index(drop=True)
# avg_scores_df.to_csv('avg_scores_df.csv', index=False)
display(avg_scores_df)

====================================================================================================
AVERAGE SCORES ACROSS ALL NOISE LEVELS
====================================================================================================

    Rank         Hyperparameters   Mean Score
0      1  QLearner_0.9_0.9_0.1_1  2558.446667
1      2  QLearner_0.5_0.5_0.1_1  2497.333333
2      3  QLearner_0.5_0.9_0.1_1  2456.036667
3      4  QLearner_0.5_0.5_0.1_2  2450.203333
4      5  QLearner_0.9_0.5_0.1_2  2405.140000
..   ...                     ...          ...
85    86    QLearner_0.1_0.5_0_5  1820.350000
86    87    QLearner_0.5_0.9_0_5  1817.756667
87    88    QLearner_0.1_0.9_0_3  1811.073333
88    89    QLearner_0.1_0.9_0_5  1801.160000
89    90    QLearner_0.1_0.9_0_4  1800.883333

[90 rows x 3 columns]