In [6]:
import sys
from pathlib import Path
import pandas as pd
from experiments import result_utils

# Configuration
dir_agent_map = {
    "bqlearning": "Jax Bayesian QLearner",
    "qlearning": "Jax QLearner",
    "actinf": "JAX_AIF",
    "dbs": "DBS"
}

results_dir = Path.cwd()

# Analyze all agents across all noise levels
print("Analyzing hyperparameter results...")
results_by_noise = result_utils.analyze_best_agents_per_noise(results_dir, dir_agent_map)

# Get top 10 agents for each noise level
top_agents = result_utils.get_top_n_agents(results_by_noise, n=100)

# Format for display
formatted_results = result_utils.format_results_for_display(top_agents, decimals=2)

print(f"Analysis complete! Found {len(formatted_results)} noise levels.")

Analyzing hyperparameter results...
Analysis complete! Found 6 noise levels.

In [7]:
# Display results as 6 separate tables (one for each noise level)
for noise_level in sorted(formatted_results.keys()):
    print(f"\n{'='*100}")
    print(f"NOISE LEVEL: {noise_level}")
    print(f"{'='*100}\n")
    
    df = formatted_results[noise_level]
    # Add rank column
    df_display = df.copy()
    df_display.insert(0, 'Rank', range(1, len(df_display) + 1))
    
    display(df_display)

====================================================================================================
NOISE LEVEL: 0.0
====================================================================================================

,Rank,Agent Type,Hyperparameters,Mean Score,Num Repetitions
0,1,DBS,DBS_0.5_1_2_1_5,2967.36,5
1,2,DBS,DBS_0.5_1_2_1_3,2967.35,5
2,3,JAX_AIF,AIF_0.5_standard_True_10_10_1,2826.80,5
3,4,JAX_AIF,AIF_1.5_standard_True_10_10_1,2826.80,5
4,5,JAX_AIF,AIF_1_standard_True_10_10_1,2826.80,5
...,...,...,...,...,...
95,96,JAX_AIF,AIF_1_nash_False_10_50_1,2275.90,5
96,97,JAX_AIF,AIF_1.5_nash_False_10_10_1,2275.85,5
97,98,JAX_AIF,AIF_0.5_nash_False_10_10_1,2275.85,5
98,99,JAX_AIF,AIF_1_nash_False_10_10_1,2275.85,5
99,100,JAX_AIF,AIF_1_nash_False_10_100_1,2246.22,5

====================================================================================================
NOISE LEVEL: 0.05
====================================================================================================

,Rank,Agent Type,Hyperparameters,Mean Score,Num Repetitions
0,1,DBS,DBS_0.999_5_2_3_5,2795.53,5
1,2,DBS,DBS_0.999_5_4_5_5,2790.70,5
2,3,DBS,DBS_0.999_5_2_5_5,2781.98,5
3,4,DBS,DBS_0.999_5_4_3_5,2778.92,5
4,5,DBS,DBS_0.999_5_2_3_3,2765.01,5
...,...,...,...,...,...
95,96,JAX_AIF,AIF_1_standard_False_1_100_1,2206.02,5
96,97,JAX_AIF,AIF_0.5_standard_False_1_100_1,2206.02,5
97,98,JAX_AIF,AIF_1.5_standard_False_1_100_1,2206.02,5
98,99,JAX_AIF,AIF_1_standard_True_1_50_1,2205.81,5
99,100,JAX_AIF,AIF_1.5_standard_True_1_50_1,2205.81,5

====================================================================================================
NOISE LEVEL: 0.1
====================================================================================================

,Rank,Agent Type,Hyperparameters,Mean Score,Num Repetitions
0,1,DBS,DBS_0.75_5_4_5_5,2676.63,5
1,2,DBS,DBS_0.999_5_2_5_5,2676.05,5
2,3,DBS,DBS_0.999_5_2_3_5,2666.03,5
3,4,DBS,DBS_0.999_5_4_5_5,2662.73,5
4,5,DBS,DBS_0.999_3_2_3_3,2662.55,5
...,...,...,...,...,...
95,96,Jax QLearner,QLearner_0.5_0.1_0.1,2222.15,5
96,97,JAX_AIF,AIF_1_standard_False_1_10_1,2221.01,5
97,98,JAX_AIF,AIF_1.5_standard_False_1_10_1,2221.01,5
98,99,JAX_AIF,AIF_0.5_standard_False_1_10_1,2221.01,5
99,100,JAX_AIF,AIF_1_standard_True_1_100_1,2219.21,5

====================================================================================================
NOISE LEVEL: 0.15
====================================================================================================

,Rank,Agent Type,Hyperparameters,Mean Score,Num Repetitions
0,1,DBS,DBS_0.999_5_2_5_5,2581.35,5
1,2,DBS,DBS_0.75_5_4_5_5,2578.80,5
2,3,DBS,DBS_0.999_5_2_3_5,2567.66,5
3,4,DBS,DBS_0.999_5_2_5_3,2565.15,5
4,5,DBS,DBS_0.999_5_2_3_3,2562.18,5
...,...,...,...,...,...
95,96,Jax Bayesian QLearner,BQLearner_0.5_0.5_1.0,2229.06,5
96,97,Jax Bayesian QLearner,BQLearner_0.5_0.5_0.5,2229.06,5
97,98,Jax Bayesian QLearner,BQLearner_0.5_0.5_0.1,2229.06,5
98,99,Jax Bayesian QLearner,BQLearner_0.9_1.0_0.1,2229.06,5
99,100,Jax Bayesian QLearner,BQLearner_0.9_0.5_1.0,2229.06,5

====================================================================================================
NOISE LEVEL: 0.2
====================================================================================================

,Rank,Agent Type,Hyperparameters,Mean Score,Num Repetitions
0,1,DBS,DBS_0.999_5_2_3_5,2467.12,5
1,2,DBS,DBS_0.999_5_2_3_3,2460.95,5
2,3,DBS,DBS_0.999_5_2_5_3,2455.37,5
3,4,DBS,DBS_0.999_5_2_5_5,2454.03,5
4,5,DBS,DBS_0.75_3_4_3_3,2446.81,5
...,...,...,...,...,...
95,96,Jax Bayesian QLearner,BQLearner_0.5_0.5_1.0,2188.62,5
96,97,Jax Bayesian QLearner,BQLearner_0.5_0.5_0.5,2188.62,5
97,98,Jax Bayesian QLearner,BQLearner_0.5_0.5_0.1,2188.62,5
98,99,Jax Bayesian QLearner,BQLearner_0.5_0.1_1.0,2188.62,5
99,100,Jax Bayesian QLearner,BQLearner_0.5_0.1_0.5,2188.62,5

====================================================================================================
NOISE LEVEL: 0.25
====================================================================================================

,Rank,Agent Type,Hyperparameters,Mean Score,Num Repetitions
0,1,DBS,DBS_0.999_5_2_3_5,2400.31,5
1,2,DBS,DBS_0.999_5_2_3_3,2399.34,5
2,3,DBS,DBS_0.999_5_4_5_5,2393.28,5
3,4,DBS,DBS_0.999_5_4_5_3,2386.92,5
4,5,DBS,DBS_0.999_5_2_5_3,2385.13,5
...,...,...,...,...,...
95,96,Jax Bayesian QLearner,BQLearner_0.5_0.5_1.0,2191.96,5
96,97,Jax Bayesian QLearner,BQLearner_0.5_0.5_0.5,2191.96,5
97,98,Jax Bayesian QLearner,BQLearner_0.5_0.5_0.1,2191.96,5
98,99,Jax Bayesian QLearner,BQLearner_0.5_0.1_1.0,2191.96,5
99,100,Jax Bayesian QLearner,BQLearner_0.5_0.1_0.5,2191.96,5

In [10]:
# Calculate average scores across all noise levels for each agent
print(f"\n{'='*100}")
print("AVERAGE SCORES ACROSS ALL NOISE LEVELS")
print(f"{'='*100}\n")

# Combine all results across noise levels
all_results = []
for noise_level, df in formatted_results.items():
    df_copy = df.copy()
    df_copy['noise_level'] = noise_level
    all_results.append(df_copy)

combined_df = pd.concat(all_results, ignore_index=True)

# Calculate average score for each agent across all noise levels
avg_scores = combined_df.groupby('Hyperparameters')['Mean Score'].mean().sort_values(ascending=False)
avg_scores_df = pd.DataFrame({
    'Hyperparameters': avg_scores.index,
    'Mean Score': avg_scores.values
})

# Add rank column
avg_scores_df.insert(0, 'Rank', range(1, len(avg_scores_df) + 1))

# Reset index for clean display
avg_scores_df = avg_scores_df.reset_index(drop=True)
avg_scores_df.to_csv('avg_scores_df.csv', index=False)
display(avg_scores_df)

====================================================================================================
AVERAGE SCORES ACROSS ALL NOISE LEVELS
====================================================================================================

     Rank                Hyperparameters   Mean Score
0       1              DBS_0.999_5_2_3_5  2612.460000
1       2              DBS_0.999_5_2_5_5  2606.366667
2       3              DBS_0.999_5_2_3_3  2599.836667
3       4              DBS_0.999_5_4_5_5  2598.145000
4       5              DBS_0.999_5_2_5_3  2592.731667
..    ...                            ...          ...
116   117  AIF_0.5_standard_True_1_100_1  2222.590000
117   118  AIF_1.5_standard_True_1_100_1  2222.590000
118   119   AIF_1.5_standard_True_1_50_1  2222.576000
119   120     AIF_1_standard_True_1_50_1  2222.576000
120   121    AIF_1_standard_True_1_100_1  2221.914000

[121 rows x 3 columns]